import type {
  DataAssigneeT,
  DataDocumentFieldT,
  DataTreeNodeT,
} from '@/features/data-management/types'

const DEMO_PDF = '/mock-data-preview.pdf'

const now = new Date().toISOString()

export const MOCK_DATA_ROOT_ID = 'dm-root'

export const MOCK_DATA_ASSIGNEES: Array<DataAssigneeT> = [
  { id: 'user-editor-1', name: 'Nguyễn Minh Anh', role: 'editor' },
  { id: 'user-editor-2', name: 'Trần Hoàng Nam', role: 'editor' },
  { id: 'user-reviewer-1', name: 'Lê Thu Hà', role: 'reviewer' },
  { id: 'user-reviewer-2', name: 'Phạm Quốc Bảo', role: 'reviewer' },
  { id: 'user-reviewer-3', name: 'Đỗ Ngọc Linh', role: 'reviewer' },
]

const MOCK_DOC_FIELDS: DataDocumentFieldT[] = [
  {
    name: 'so_ban_an',
    display: 'Số bản án',
    type: 'string',
    value: '12/201',
    page: 1,
    bbox: [571.0, 1435.0, 2684.0, 1546.0],
  },
  {
    name: 'ngay_ban_hanh',
    display: 'Ngày ban hành',
    type: 'date',
    value: '2024-01-16',
    page: 1,
    bbox: [1603.0, 579.0, 2551.0, 668.0],
  },
  {
    name: 'so_quyet_dinh_tha',
    display: 'Số quyết định THA',
    type: 'string',
    value: '13',
    page: 1,
    bbox: [659.0, 583.0, 1161.0, 668.0],
  },
  {
    name: 'ngay_quyet_dinh_tha',
    display: 'Ngày quyết định THA',
    type: 'date',
    value: '2024-01-14',
    page: 1,
    bbox: [394.0, 1334.0, 1838.0, 1431.0],
  },
  {
    name: 'ngay_hieu_luc',
    display: 'Ngày hiệu lực',
    type: 'date',
    value: '2024-02-06',
    page: 1,
    bbox: [1603.0, 579.0, 2551.0, 668.0],
  },
]

const MOCK_RECORD_FIELDS: DataDocumentFieldT[] = [
  {
    name: 'ma_ho_so',
    display: 'Mã hồ sơ',
    type: 'string',
    value: 'HS-2024-001',
    page: 1,
    bbox: [],
  },
  {
    name: 'chu_de',
    display: 'Chủ đề',
    type: 'string',
    value: 'Hợp đồng thuê nhà',
    page: 1,
    bbox: [],
  },
  {
    name: 'ngay_tao',
    display: 'Ngày tạo',
    type: 'date',
    value: '2024-01-10',
    page: 1,
    bbox: [],
  },
  {
    name: 'tong_tien',
    display: 'Tổng tiền',
    type: 'number',
    value: '50000000',
    page: 1,
    bbox: [],
  },
]

export function createSeedDataTree(): DataTreeNodeT {
  return {
    id: MOCK_DATA_ROOT_ID,
    name: 'root',
    type: 'record',
    parentId: null,
    sizeBytes: 0,
    uploadedAt: now,
    uploadedBy: 'Admin Demo',
    fields: MOCK_RECORD_FIELDS,
    children: [
      {
        id: 'dm-record-a',
        name: 'Hồ sơ A',
        type: 'record',
        parentId: MOCK_DATA_ROOT_ID,
        sizeBytes: 245_760,
        uploadedAt: now,
        uploadedBy: 'Admin Demo',
        recordStatus: 'pendingOcr',
        fields: MOCK_RECORD_FIELDS,
        children: [
          {
            id: 'dm-doc-a1',
            name: 'Báo cáo.pdf',
            type: 'document',
            parentId: 'dm-record-a',
            children: [],
            sizeBytes: 132_000,
            uploadedAt: now,
            uploadedBy: 'Admin Demo',
            mimeType: 'application/pdf',
            fileUrl: DEMO_PDF,
            fields: MOCK_DOC_FIELDS,
          },
          {
            id: 'dm-doc-a2',
            name: 'Phụ lục.pdf',
            type: 'document',
            parentId: 'dm-record-a',
            children: [],
            sizeBytes: 113_760,
            uploadedAt: now,
            uploadedBy: 'Admin Demo',
            mimeType: 'application/pdf',
            fileUrl: DEMO_PDF,
            fields: MOCK_DOC_FIELDS,
          },
        ],
      },
      {
        id: 'dm-folder-b',
        name: 'Thư mục 1',
        type: 'folder',
        parentId: MOCK_DATA_ROOT_ID,
        sizeBytes: 0,
        uploadedAt: now,
        uploadedBy: 'Admin Demo',
        children: [
          {
            id: 'dm-record-b',
            name: 'Hồ sơ B',
            type: 'record',
            parentId: 'dm-folder-b',
            sizeBytes: 88_000,
            uploadedAt: now,
            uploadedBy: 'Admin Demo',
            recordStatus: 'pendingApproval',
            editor: MOCK_DATA_ASSIGNEES[1],
            fields: MOCK_RECORD_FIELDS,
            children: [
              {
                id: 'dm-doc-b1',
                name: 'Tài liệu nội bộ.pdf',
                type: 'document',
                parentId: 'dm-record-b',
                children: [],
                sizeBytes: 88_000,
                uploadedAt: now,
                uploadedBy: 'Admin Demo',
                mimeType: 'application/pdf',
                fileUrl: DEMO_PDF,
                fields: MOCK_DOC_FIELDS,
              },
            ],
          },
        ],
      },
      {
        id: 'dm-record-c',
        name: 'Hồ sơ C',
        type: 'record',
        parentId: MOCK_DATA_ROOT_ID,
        sizeBytes: 96_000,
        uploadedAt: now,
        uploadedBy: 'Admin Demo',
        recordStatus: 'approved2',
        editor: MOCK_DATA_ASSIGNEES[0],
        reviewer1: MOCK_DATA_ASSIGNEES[2],
        reviewer2: MOCK_DATA_ASSIGNEES[3],
        fields: MOCK_RECORD_FIELDS,
        children: [
          {
            id: 'dm-doc-c1',
            name: 'Biên bản nghiệm thu.pdf',
            type: 'document',
            parentId: 'dm-record-c',
            children: [],
            sizeBytes: 96_000,
            uploadedAt: now,
            uploadedBy: 'Admin Demo',
            mimeType: 'application/pdf',
            fileUrl: DEMO_PDF,
            fields: MOCK_DOC_FIELDS,
          },
        ],
      },
      {
        id: 'dm-record-d',
        name: 'Hồ sơ D',
        type: 'record',
        parentId: MOCK_DATA_ROOT_ID,
        sizeBytes: 124_000,
        uploadedAt: now,
        uploadedBy: 'Admin Demo',
        recordStatus: 'completed',
        editor: MOCK_DATA_ASSIGNEES[1],
        reviewer1: MOCK_DATA_ASSIGNEES[2],
        reviewer2: MOCK_DATA_ASSIGNEES[3],
        reviewer3: MOCK_DATA_ASSIGNEES[4],
        fields: MOCK_RECORD_FIELDS,
        children: [
          {
            id: 'dm-doc-d1',
            name: 'Quyết định.pdf',
            type: 'document',
            parentId: 'dm-record-d',
            children: [],
            sizeBytes: 124_000,
            uploadedAt: now,
            uploadedBy: 'Admin Demo',
            mimeType: 'application/pdf',
            fileUrl: DEMO_PDF,
            fields: MOCK_DOC_FIELDS,
          },
        ],
      },
      {
        id: 'dm-folder-1',
        name: 'Thư mục',
        type: 'folder',
        parentId: MOCK_DATA_ROOT_ID,
        sizeBytes: 0,
        uploadedAt: now,
        uploadedBy: 'Admin Demo',
        children: [],
      },
    ],
  }
}
