import type { AuditRouteDefinition } from "./audit-route-types.ts";
import {
    enrichArchiveDeleteFile,
    enrichArchiveMoveFile,
    enrichArchiveUpdateFileDocumentType,
    enrichInventoryCrud,
    enrichPhysicalPlacementMove,
    enrichPhysicalPlacementPlace,
    enrichPhysicalPlacementRemove,
    enrichPhysicalWarehouseItemCrud,
    enrichPhysicalWarehouseReparent,
} from "./audit-route-enrichers.ts";

export const AUDIT_ROUTE_REGISTRY: AuditRouteDefinition[] = [
    {
        method: "POST",
        pattern: "/inventories",
        module: "inventories",
        eventType: "create",
        enrich: enrichInventoryCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/inventories/:id",
        module: "inventories",
        eventType: "update",
        enrich: enrichInventoryCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/inventories/:id",
        module: "inventories",
        eventType: "delete",
        enrich: enrichInventoryCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/items",
        module: "physical-warehouse",
        eventType: "create",
        enrich: enrichPhysicalWarehouseItemCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/physical-warehouse/items/:id",
        module: "physical-warehouse",
        eventType: "update",
        enrich: enrichPhysicalWarehouseItemCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/physical-warehouse/items/:id",
        module: "physical-warehouse",
        eventType: "delete",
        enrich: enrichPhysicalWarehouseItemCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/items/:id/reparent",
        module: "physical-warehouse",
        eventType: "reparent",
        enrich: enrichPhysicalWarehouseReparent,
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/placements",
        module: "archive",
        eventType: "place_physical",
        enrich: enrichPhysicalPlacementPlace,
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/placements/move",
        module: "archive",
        eventType: "move_physical",
        enrich: enrichPhysicalPlacementMove,
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/placements/remove",
        module: "archive",
        eventType: "remove_physical",
        enrich: enrichPhysicalPlacementRemove,
    },
    {
        method: "POST",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/:fileId/move",
        module: "archive",
        eventType: "move_file",
        enrich: enrichArchiveMoveFile,
    },
    {
        method: "POST",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/bulk-move",
        module: "archive",
        eventType: "move_file",
        enrich: enrichArchiveMoveFile,
    },
    {
        method: "DELETE",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/:fileId",
        module: "archive",
        eventType: "delete_file",
        enrich: enrichArchiveDeleteFile,
    },
    {
        method: "POST",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/bulk-delete",
        module: "archive",
        eventType: "delete_file",
        enrich: enrichArchiveDeleteFile,
    },
    {
        method: "PATCH",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/:fileId/document-type",
        module: "archive",
        eventType: "update_file",
        enrich: enrichArchiveUpdateFileDocumentType,
    },
];
