import type { AuditRouteDefinition } from "./audit-route-types.ts";
import {
    enrichArchiveAclCrud,
    enrichArchiveBorrowActivate,
    enrichArchiveBorrowApprove,
    enrichArchiveBorrowCreate,
    enrichArchiveBorrowRegenerateDip,
    enrichArchiveBorrowReject,
    enrichArchiveBorrowViewDocument,
    enrichArchiveDeleteFile,
    enrichArchiveDisposalAction,
    enrichArchiveMoveFile,
    enrichArchiveUpdateFileDocumentType,
    enrichDataEntryApprove,
    enrichDataEntryBulkSubmit,
    enrichDataEntryReject,
    enrichDataEntrySubmitMetadata,
    enrichDigitalSignPrepare,
    enrichDigitalSignSubmit,
    enrichDigitalSignVerify,
    enrichDocumentNamingConfigCrud,
    enrichDocumentTypeCrud,
    enrichDossierCrud,
    enrichDossierTypeCrud,
    enrichFolderAssignProject,
    enrichFolderCrud,
    enrichFondCrud,
    enrichGroupCrud,
    enrichInventoryCrud,
    enrichIssueReportAction,
    enrichMetadataExportPresetCrud,
    enrichMetadataPermissionConfigCrud,
    enrichMetadataTemplateCrud,
    enrichPhysicalPlacementMove,
    enrichPhysicalPlacementPlace,
    enrichPhysicalPlacementRemove,
    enrichPhysicalWarehouseItemCrud,
    enrichPhysicalWarehouseReparent,
    enrichProjectCrud,
    enrichProjectPlanCrud,
    enrichRetentionPeriodCrud,
    enrichRolePermissionsUpdate,
    enrichRolePermissionsView,
    enrichScanIntakePromote,
    enrichScanIntakeSessionDelete,
    enrichSecurityLevelCrud,
    enrichSecurityLevelVerify,
    enrichUserStatusUpdate,
} from "./audit-route-enrichers.ts";


export const AUDIT_ROUTE_REGISTRY: AuditRouteDefinition[] = [
    {
        method: "POST",
        pattern: "/inventories",
        module: "inventories",
        eventType: "create",
        enrich: enrichInventoryCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/inventories/:id",
        module: "inventories",
        eventType: "update",
        enrich: enrichInventoryCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/inventories/:id",
        module: "inventories",
        eventType: "delete",
        enrich: enrichInventoryCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/items",
        module: "physical-warehouse",
        eventType: "create",
        enrich: enrichPhysicalWarehouseItemCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/physical-warehouse/items/:id",
        module: "physical-warehouse",
        eventType: "update",
        enrich: enrichPhysicalWarehouseItemCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/physical-warehouse/items/:id",
        module: "physical-warehouse",
        eventType: "delete",
        enrich: enrichPhysicalWarehouseItemCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/items/:id/reparent",
        module: "physical-warehouse",
        eventType: "reparent",
        enrich: enrichPhysicalWarehouseReparent,
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/placements",
        module: "archive",
        eventType: "place_physical",
        enrich: enrichPhysicalPlacementPlace,
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/placements/move",
        module: "archive",
        eventType: "move_physical",
        enrich: enrichPhysicalPlacementMove,
    },
    {
        method: "POST",
        pattern: "/physical-warehouse/placements/remove",
        module: "archive",
        eventType: "remove_physical",
        enrich: enrichPhysicalPlacementRemove,
    },
    {
        method: "POST",
        pattern: "/archive-submissions/physical-location/place",
        module: "archive",
        eventType: "place_physical",
        enrich: enrichPhysicalPlacementPlace,
    },
    {
        method: "POST",
        pattern: "/archive-submissions/physical-location/move",
        module: "archive",
        eventType: "move_physical",
        enrich: enrichPhysicalPlacementMove,
    },
    {
        method: "POST",
        pattern: "/archive-submissions/physical-location/remove",
        module: "archive",
        eventType: "remove_physical",
        enrich: enrichPhysicalPlacementRemove,
    },
    {
        method: "POST",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/:fileId/move",
        module: "archive",
        eventType: "move_file",
        enrich: enrichArchiveMoveFile,
    },
    {
        method: "POST",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/bulk-move",
        module: "archive",
        eventType: "move_file",
        enrich: enrichArchiveMoveFile,
    },
    {
        method: "DELETE",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/:fileId",
        module: "archive",
        eventType: "delete_file",
        enrich: enrichArchiveDeleteFile,
    },
    {
        method: "POST",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/bulk-delete",
        module: "archive",
        eventType: "delete_file",
        enrich: enrichArchiveDeleteFile,
    },
    {
        method: "PATCH",
        pattern: "/archive-warehouse/dossiers/:dossierId/files/:fileId/document-type",
        module: "archive",
        eventType: "update_file",
        enrich: enrichArchiveUpdateFileDocumentType,
    },
    {
        method: "POST",
        pattern: "/data-entry/checker/approve/:dossierId",
        module: "data-entry",
        eventType: "approve",
        enrich: enrichDataEntryApprove,
    },
    {
        method: "POST",
        pattern: "/data-entry/checker/reject/:dossierId",
        module: "data-entry",
        eventType: "reject",
        enrich: enrichDataEntryReject,
    },
    {
        method: "PUT",
        pattern: "/dossiers/:id/metadata",
        module: "data-entry",
        eventType: "edit",
        enrich: enrichDataEntrySubmitMetadata,
    },
    {
        method: "POST",
        pattern: "/dossiers/assignments/drafts/submit",
        module: "data-entry",
        eventType: "edit",
        enrich: enrichDataEntryBulkSubmit,
    },
    {
        method: "PATCH",
        pattern: "/admin/users/:id/status",
        module: "users",
        eventType: "update",
        enrich: enrichUserStatusUpdate,
    },
    {
        method: "GET",
        pattern: "/admin/roles/:id/permissions",
        module: "roles",
        eventType: "view",
        enrich: enrichRolePermissionsView,
    },
    {
        method: "PUT",
        pattern: "/admin/roles/:id/permissions",
        module: "roles",
        eventType: "permission_change",
        enrich: enrichRolePermissionsUpdate,
    },
    {
        method: "POST",
        pattern: "/fonds",
        module: "fonds",
        eventType: "create",
        enrich: enrichFondCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/fonds/:id",
        module: "fonds",
        eventType: "update",
        enrich: enrichFondCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/fonds/:id",
        module: "fonds",
        eventType: "delete",
        enrich: enrichFondCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/retention-periods",
        module: "retention-periods",
        eventType: "create",
        enrich: enrichRetentionPeriodCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/retention-periods/:id",
        module: "retention-periods",
        eventType: "update",
        enrich: enrichRetentionPeriodCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/retention-periods/:id",
        module: "retention-periods",
        eventType: "delete",
        enrich: enrichRetentionPeriodCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/folders",
        module: "folders",
        eventType: "create",
        enrich: enrichFolderCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/folders/:id",
        module: "folders",
        eventType: "update",
        enrich: enrichFolderCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/folders/:id",
        module: "folders",
        eventType: "delete",
        enrich: enrichFolderCrud("delete"),
    },
    {
        method: "PUT",
        pattern: "/folders/:id/project",
        module: "folders",
        eventType: "assign",
        enrich: enrichFolderAssignProject,
    },
    {
        method: "POST",
        pattern: "/dossiers",
        module: "archive",
        eventType: "create",
        enrich: enrichDossierCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/dossiers/:id",
        module: "archive",
        eventType: "update",
        enrich: enrichDossierCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/dossiers/:id",
        module: "archive",
        eventType: "delete",
        enrich: enrichDossierCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/dossier-types",
        module: "dossier-types",
        eventType: "create",
        enrich: enrichDossierTypeCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/dossier-types/:id",
        module: "dossier-types",
        eventType: "update",
        enrich: enrichDossierTypeCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/dossier-types/:id",
        module: "dossier-types",
        eventType: "delete",
        enrich: enrichDossierTypeCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/document-types",
        module: "document-types",
        eventType: "create",
        enrich: enrichDocumentTypeCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/document-types/:id",
        module: "document-types",
        eventType: "update",
        enrich: enrichDocumentTypeCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/document-types/:id",
        module: "document-types",
        eventType: "delete",
        enrich: enrichDocumentTypeCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/scan-intake/promote",
        module: "scan-intake",
        eventType: "promote",
        enrich: enrichScanIntakePromote,
    },
    {
        method: "POST",
        pattern: "/scan-intake/session/delete",
        module: "scan-intake",
        eventType: "delete",
        enrich: enrichScanIntakeSessionDelete,
    },
    {
        method: "POST",
        pattern: "/digital-sign/prepare",
        module: "digital-sign",
        eventType: "prepare",
        enrich: enrichDigitalSignPrepare,
    },
    {
        method: "POST",
        pattern: "/digital-sign/batch/prepare",
        module: "digital-sign",
        eventType: "prepare",
        enrich: enrichDigitalSignPrepare,
    },
    {
        method: "POST",
        pattern: "/digital-sign/submit",
        module: "digital-sign",
        eventType: "submit",
        enrich: enrichDigitalSignSubmit,
    },
    {
        method: "POST",
        pattern: "/digital-sign/batch/submit",
        module: "digital-sign",
        eventType: "submit",
        enrich: enrichDigitalSignSubmit,
    },
    {
        method: "POST",
        pattern: "/digital-sign/verify/:fileId",
        module: "digital-sign",
        eventType: "verify",
        enrich: enrichDigitalSignVerify,
    },
    {
        method: "POST",
        pattern: "/issue-reports/:reportId/confirm",
        module: "issue-reports",
        eventType: "confirm",
        enrich: enrichIssueReportAction("confirm"),
    },
    {
        method: "POST",
        pattern: "/issue-reports/:reportId/reject",
        module: "issue-reports",
        eventType: "reject",
        enrich: enrichIssueReportAction("reject"),
    },
    {
        method: "POST",
        pattern: "/issue-reports/:reportId/escalate",
        module: "issue-reports",
        eventType: "escalate",
        enrich: enrichIssueReportAction("escalate"),
    },
    {
        method: "POST",
        pattern: "/admin/metadata-templates",
        module: "metadata",
        eventType: "template_change",
        enrich: enrichMetadataTemplateCrud("create"),
    },
    {
        method: "PATCH",
        pattern: "/admin/metadata-templates/:id",
        module: "metadata",
        eventType: "template_change",
        enrich: enrichMetadataTemplateCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/admin/metadata-templates/:id",
        module: "metadata",
        eventType: "template_change",
        enrich: enrichMetadataTemplateCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/admin/metadata-permission-configs",
        module: "metadata",
        eventType: "permission_change",
        enrich: enrichMetadataPermissionConfigCrud("create"),
    },
    {
        method: "PATCH",
        pattern: "/admin/metadata-permission-configs/:id",
        module: "metadata",
        eventType: "permission_change",
        enrich: enrichMetadataPermissionConfigCrud("update"),
    },
    {
        method: "PUT",
        pattern: "/admin/metadata-permission-configs/:id/slots",
        module: "metadata",
        eventType: "permission_change",
        enrich: enrichMetadataPermissionConfigCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/admin/metadata-permission-configs/:id",
        module: "metadata",
        eventType: "permission_change",
        enrich: enrichMetadataPermissionConfigCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/admin/metadata-export-presets",
        module: "metadata",
        eventType: "export_preset_change",
        enrich: enrichMetadataExportPresetCrud("create"),
    },
    {
        method: "PATCH",
        pattern: "/admin/metadata-export-presets/:id",
        module: "metadata",
        eventType: "export_preset_change",
        enrich: enrichMetadataExportPresetCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/admin/metadata-export-presets/:id",
        module: "metadata",
        eventType: "export_preset_change",
        enrich: enrichMetadataExportPresetCrud("delete"),
    },
    {
        method: "PUT",
        pattern: "/admin/document-naming-configs",
        module: "metadata",
        eventType: "naming_change",
        enrich: enrichDocumentNamingConfigCrud("update"),
    },
    {
        method: "POST",
        pattern: "/admin/groups",
        module: "groups",
        eventType: "create",
        enrich: enrichGroupCrud("create"),
    },
    {
        method: "PATCH",
        pattern: "/admin/groups/:id",
        module: "groups",
        eventType: "update",
        enrich: enrichGroupCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/admin/groups/:id",
        module: "groups",
        eventType: "delete",
        enrich: enrichGroupCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/admin/projects",
        module: "projects",
        eventType: "create",
        enrich: enrichProjectCrud("create"),
    },
    {
        method: "PATCH",
        pattern: "/admin/projects/:id",
        module: "projects",
        eventType: "update",
        enrich: enrichProjectCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/admin/projects/:id",
        module: "projects",
        eventType: "delete",
        enrich: enrichProjectCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/security-levels",
        module: "security-levels",
        eventType: "create",
        enrich: enrichSecurityLevelCrud("create"),
    },
    {
        method: "PUT",
        pattern: "/security-levels/:id",
        module: "security-levels",
        eventType: "update",
        enrich: enrichSecurityLevelCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/security-levels/:id",
        module: "security-levels",
        eventType: "delete",
        enrich: enrichSecurityLevelCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/security-levels/verify-access",
        module: "security-levels",
        eventType: "verify",
        enrich: enrichSecurityLevelVerify,
    },
    {
        method: "PUT",
        pattern: "/admin/archive-acl/principals",
        module: "archive",
        eventType: "update",
        enrich: enrichArchiveAclCrud("update"),
    },
    {
        method: "PUT",
        pattern: "/admin/archive-acl/metadata-view/:documentTypeId",
        module: "archive",
        eventType: "update",
        enrich: enrichArchiveAclCrud("update"),
    },
    {
        method: "POST",
        pattern: "/archive-borrow-requests",
        module: "archive-borrow",
        eventType: "request_borrow",
        enrich: enrichArchiveBorrowCreate,
    },
    {
        method: "POST",
        pattern: "/archive-borrow-requests/:id/approve",
        module: "archive-borrow",
        eventType: "approve_borrow",
        enrich: enrichArchiveBorrowApprove,
    },
    {
        method: "POST",
        pattern: "/archive-borrow-requests/:id/reject",
        module: "archive-borrow",
        eventType: "reject_borrow",
        enrich: enrichArchiveBorrowReject,
    },
    {
        method: "POST",
        pattern: "/archive-borrow-requests/:id/regenerate-dip",
        module: "archive-borrow",
        eventType: "regenerate_borrow_dip",
        enrich: enrichArchiveBorrowRegenerateDip,
    },
    {
        method: "POST",
        pattern: "/archive-borrow-requests/:id/activate",
        module: "archive-borrow",
        eventType: "activate_borrow",
        enrich: enrichArchiveBorrowActivate,
    },
    {
        method: "GET",
        pattern: "/archive-borrow-requests/:id/dip/files/:fileId/content",
        module: "archive-borrow",
        eventType: "view_borrow_document",
        enrich: enrichArchiveBorrowViewDocument,
    },
    {
        method: "POST",
        pattern: "/project-plans",
        module: "project-plans",
        eventType: "create",
        enrich: enrichProjectPlanCrud("create"),
    },
    {
        method: "PATCH",
        pattern: "/project-plans/:id",
        module: "project-plans",
        eventType: "update",
        enrich: enrichProjectPlanCrud("update"),
    },
    {
        method: "PUT",
        pattern: "/project-plans/:id",
        module: "project-plans",
        eventType: "update",
        enrich: enrichProjectPlanCrud("update"),
    },
    {
        method: "DELETE",
        pattern: "/project-plans/:id",
        module: "project-plans",
        eventType: "delete",
        enrich: enrichProjectPlanCrud("delete"),
    },
    {
        method: "POST",
        pattern: "/archive-disposal/proposals",
        module: "archive-disposal",
        eventType: "create",
        enrich: enrichArchiveDisposalAction("create"),
    },
    {
        method: "PUT",
        pattern: "/archive-disposal/proposals/:id",
        module: "archive-disposal",
        eventType: "update",
        enrich: enrichArchiveDisposalAction("update"),
    },
    {
        method: "POST",
        pattern: "/archive-disposal/proposals/:id/submit",
        module: "archive-disposal",
        eventType: "submit",
        enrich: enrichArchiveDisposalAction("submit"),
    },
    {
        method: "POST",
        pattern: "/archive-disposal/councils",
        module: "archive-disposal",
        eventType: "council_create",
        enrich: enrichArchiveDisposalAction("council_create"),
    },
    {
        method: "POST",
        pattern: "/archive-disposal/councils/:id/finalize",
        module: "archive-disposal",
        eventType: "council_finalize",
        enrich: enrichArchiveDisposalAction("council_finalize"),
    },
    {
        method: "POST",
        pattern: "/archive-disposal/councils/:id/publish",
        module: "archive-disposal",
        eventType: "council_publish",
        enrich: enrichArchiveDisposalAction("council_publish"),
    },
    {
        method: "POST",
        pattern: "/archive-disposal/destroy",
        module: "archive-disposal",
        eventType: "destroy",
        enrich: enrichArchiveDisposalAction("destroy"),
    },
];

