services:
  server:
    build: 
      context: ../../
      dockerfile: packages/sohoa-backend/Dockerfile
    container_name: sohoa-server
    restart: always
    network_mode: "host" 
    environment:
      - NODE_ENV=production
      - PORT=8000 # Cổng chạy của Backend ngoài máy chủ
      - DB_SCHEMA=sohoa_app
      - DATABASE_URL=postgresql://postgres:postgres@10.10.6.134:54322/sohoa
      - S3='{"endPoint":"10.10.6.134","port":9000,"useSSL":false,"accessKey":"admin","secretKey":"Admin@123","bucket":"data-lake","region":"","maxFileSize":419430400}'