/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QcRouteRouteImport } from './routes/qc/route'
import { Route as EditorRouteRouteImport } from './routes/editor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as QcKpiIndexRouteImport } from './routes/qc/kpi/index'
import { Route as QcDataIndexRouteImport } from './routes/qc/data/index'
import { Route as EditorReviewIndexRouteImport } from './routes/editor/review/index'
import { Route as EditorKpiIndexRouteImport } from './routes/editor/kpi/index'
import { Route as EditorDataIndexRouteImport } from './routes/editor/data/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminGroupsIndexRouteImport } from './routes/admin/groups/index'
import { Route as AdminDataIndexRouteImport } from './routes/admin/data/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRouteRoute = QcRouteRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRouteRoute = EditorRouteRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const QcKpiIndexRoute = QcKpiIndexRouteImport.update({
  id: '/kpi/',
  path: '/kpi/',
  getParentRoute: () => QcRouteRoute,
} as any)
const QcDataIndexRoute = QcDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => QcRouteRoute,
} as any)
const EditorReviewIndexRoute = EditorReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => EditorRouteRoute,
} as any)
const EditorKpiIndexRoute = EditorKpiIndexRouteImport.update({
  id: '/kpi/',
  path: '/kpi/',
  getParentRoute: () => EditorRouteRoute,
} as any)
const EditorDataIndexRoute = EditorDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => EditorRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroupsIndexRoute = AdminGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataIndexRoute = AdminDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/editor': typeof EditorRouteRouteWithChildren
  '/qc': typeof QcRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/data': typeof AdminDataIndexRoute
  '/admin/groups': typeof AdminGroupsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/editor/data': typeof EditorDataIndexRoute
  '/editor/kpi': typeof EditorKpiIndexRoute
  '/editor/review': typeof EditorReviewIndexRoute
  '/qc/data': typeof QcDataIndexRoute
  '/qc/kpi': typeof QcKpiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRouteWithChildren
  '/qc': typeof QcRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/admin': typeof AdminIndexRoute
  '/admin/data': typeof AdminDataIndexRoute
  '/admin/groups': typeof AdminGroupsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/editor/data': typeof EditorDataIndexRoute
  '/editor/kpi': typeof EditorKpiIndexRoute
  '/editor/review': typeof EditorReviewIndexRoute
  '/qc/data': typeof QcDataIndexRoute
  '/qc/kpi': typeof QcKpiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/editor': typeof EditorRouteRouteWithChildren
  '/qc': typeof QcRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/data/': typeof AdminDataIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/editor/data/': typeof EditorDataIndexRoute
  '/editor/kpi/': typeof EditorKpiIndexRoute
  '/editor/review/': typeof EditorReviewIndexRoute
  '/qc/data/': typeof QcDataIndexRoute
  '/qc/kpi/': typeof QcKpiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/editor'
    | '/qc'
    | '/login'
    | '/test'
    | '/admin/'
    | '/admin/data'
    | '/admin/groups'
    | '/admin/users'
    | '/editor/data'
    | '/editor/kpi'
    | '/editor/review'
    | '/qc/data'
    | '/qc/kpi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/qc'
    | '/login'
    | '/test'
    | '/admin'
    | '/admin/data'
    | '/admin/groups'
    | '/admin/users'
    | '/editor/data'
    | '/editor/kpi'
    | '/editor/review'
    | '/qc/data'
    | '/qc/kpi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/editor'
    | '/qc'
    | '/login'
    | '/test'
    | '/admin/'
    | '/admin/data/'
    | '/admin/groups/'
    | '/admin/users/'
    | '/editor/data/'
    | '/editor/kpi/'
    | '/editor/review/'
    | '/qc/data/'
    | '/qc/kpi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EditorRouteRoute: typeof EditorRouteRouteWithChildren
  QcRouteRoute: typeof QcRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/qc/kpi/': {
      id: '/qc/kpi/'
      path: '/kpi'
      fullPath: '/qc/kpi'
      preLoaderRoute: typeof QcKpiIndexRouteImport
      parentRoute: typeof QcRouteRoute
    }
    '/qc/data/': {
      id: '/qc/data/'
      path: '/data'
      fullPath: '/qc/data'
      preLoaderRoute: typeof QcDataIndexRouteImport
      parentRoute: typeof QcRouteRoute
    }
    '/editor/review/': {
      id: '/editor/review/'
      path: '/review'
      fullPath: '/editor/review'
      preLoaderRoute: typeof EditorReviewIndexRouteImport
      parentRoute: typeof EditorRouteRoute
    }
    '/editor/kpi/': {
      id: '/editor/kpi/'
      path: '/kpi'
      fullPath: '/editor/kpi'
      preLoaderRoute: typeof EditorKpiIndexRouteImport
      parentRoute: typeof EditorRouteRoute
    }
    '/editor/data/': {
      id: '/editor/data/'
      path: '/data'
      fullPath: '/editor/data'
      preLoaderRoute: typeof EditorDataIndexRouteImport
      parentRoute: typeof EditorRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/groups/': {
      id: '/admin/groups/'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data/': {
      id: '/admin/data/'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDataIndexRoute: typeof AdminDataIndexRoute
  AdminGroupsIndexRoute: typeof AdminGroupsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminDataIndexRoute: AdminDataIndexRoute,
  AdminGroupsIndexRoute: AdminGroupsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EditorRouteRouteChildren {
  EditorDataIndexRoute: typeof EditorDataIndexRoute
  EditorKpiIndexRoute: typeof EditorKpiIndexRoute
  EditorReviewIndexRoute: typeof EditorReviewIndexRoute
}

const EditorRouteRouteChildren: EditorRouteRouteChildren = {
  EditorDataIndexRoute: EditorDataIndexRoute,
  EditorKpiIndexRoute: EditorKpiIndexRoute,
  EditorReviewIndexRoute: EditorReviewIndexRoute,
}

const EditorRouteRouteWithChildren = EditorRouteRoute._addFileChildren(
  EditorRouteRouteChildren,
)

interface QcRouteRouteChildren {
  QcDataIndexRoute: typeof QcDataIndexRoute
  QcKpiIndexRoute: typeof QcKpiIndexRoute
}

const QcRouteRouteChildren: QcRouteRouteChildren = {
  QcDataIndexRoute: QcDataIndexRoute,
  QcKpiIndexRoute: QcKpiIndexRoute,
}

const QcRouteRouteWithChildren =
  QcRouteRoute._addFileChildren(QcRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EditorRouteRoute: EditorRouteRouteWithChildren,
  QcRouteRoute: QcRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
