/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWarehouseManagementIndexRouteImport } from './routes/app/warehouse-management/index'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppScanIntakeIndexRouteImport } from './routes/app/scan-intake/index'
import { Route as AppReviewIndexRouteImport } from './routes/app/review/index'
import { Route as AppRetentionPeriodsIndexRouteImport } from './routes/app/retention-periods/index'
import { Route as AppProjectManagerIndexRouteImport } from './routes/app/project-manager/index'
import { Route as AppPlanManagementIndexRouteImport } from './routes/app/plan-management/index'
import { Route as AppPhysicalWarehouseIndexRouteImport } from './routes/app/physical-warehouse/index'
import { Route as AppPermissionsIndexRouteImport } from './routes/app/permissions/index'
import { Route as AppKpiIndexRouteImport } from './routes/app/kpi/index'
import { Route as AppInventoriesIndexRouteImport } from './routes/app/inventories/index'
import { Route as AppGroupsIndexRouteImport } from './routes/app/groups/index'
import { Route as AppGeneralCatalogIndexRouteImport } from './routes/app/general-catalog/index'
import { Route as AppDossiersIndexRouteImport } from './routes/app/dossiers/index'
import { Route as AppDossierTypesIndexRouteImport } from './routes/app/dossier-types/index'
import { Route as AppDataIndexRouteImport } from './routes/app/data/index'
import { Route as AppDataConfigIndexRouteImport } from './routes/app/data-config/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppArchiveWarehouseIndexRouteImport } from './routes/app/archive-warehouse/index'
import { Route as AppArchiveSubmissionIndexRouteImport } from './routes/app/archive-submission/index'
import { Route as AppArchiveReviewIndexRouteImport } from './routes/app/archive-review/index'
import { Route as AppArchivePermissionIndexRouteImport } from './routes/app/archive-permission/index'
import { Route as AppArchiveFondsIndexRouteImport } from './routes/app/archive-fonds/index'
import { Route as AppArchiveDossiersIndexRouteImport } from './routes/app/archive-dossiers/index'
import { Route as AppArchiveConfigIndexRouteImport } from './routes/app/archive-config/index'
import { Route as AppPlanManagementPlanIdRouteImport } from './routes/app/plan-management/$planId'
import { Route as AppPhysicalWarehouseConfigRouteImport } from './routes/app/physical-warehouse/config'
import { Route as AppPermissionsFunctionMatrixRouteImport } from './routes/app/permissions/function-matrix'
import { Route as AppGroupsGroupIdRouteImport } from './routes/app/groups/$groupId'
import { Route as AppDataConfigWatermarkConfigsRouteImport } from './routes/app/data-config/watermark-configs'
import { Route as AppDataConfigNotificationConfigsRouteImport } from './routes/app/data-config/notification-configs'
import { Route as AppDataConfigMetadataExportPresetsRouteImport } from './routes/app/data-config/metadata-export-presets'
import { Route as AppDataConfigDocumentTypesRouteImport } from './routes/app/data-config/document-types'
import { Route as AppDataConfigDocumentAssignmentRouteImport } from './routes/app/data-config/document-assignment'
import { Route as AppArchiveDossiersFondIdIndexRouteImport } from './routes/app/archive-dossiers/$fondId/index'
import { Route as AppArchiveDossiersFondIdDossierIdRouteImport } from './routes/app/archive-dossiers/$fondId/$dossierId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWarehouseManagementIndexRoute =
  AppWarehouseManagementIndexRouteImport.update({
    id: '/warehouse-management/',
    path: '/warehouse-management/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScanIntakeIndexRoute = AppScanIntakeIndexRouteImport.update({
  id: '/scan-intake/',
  path: '/scan-intake/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReviewIndexRoute = AppReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRetentionPeriodsIndexRoute =
  AppRetentionPeriodsIndexRouteImport.update({
    id: '/retention-periods/',
    path: '/retention-periods/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProjectManagerIndexRoute = AppProjectManagerIndexRouteImport.update({
  id: '/project-manager/',
  path: '/project-manager/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlanManagementIndexRoute = AppPlanManagementIndexRouteImport.update({
  id: '/plan-management/',
  path: '/plan-management/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPhysicalWarehouseIndexRoute =
  AppPhysicalWarehouseIndexRouteImport.update({
    id: '/physical-warehouse/',
    path: '/physical-warehouse/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPermissionsIndexRoute = AppPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKpiIndexRoute = AppKpiIndexRouteImport.update({
  id: '/kpi/',
  path: '/kpi/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoriesIndexRoute = AppInventoriesIndexRouteImport.update({
  id: '/inventories/',
  path: '/inventories/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGeneralCatalogIndexRoute = AppGeneralCatalogIndexRouteImport.update({
  id: '/general-catalog/',
  path: '/general-catalog/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDossiersIndexRoute = AppDossiersIndexRouteImport.update({
  id: '/dossiers/',
  path: '/dossiers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDossierTypesIndexRoute = AppDossierTypesIndexRouteImport.update({
  id: '/dossier-types/',
  path: '/dossier-types/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDataIndexRoute = AppDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDataConfigIndexRoute = AppDataConfigIndexRouteImport.update({
  id: '/data-config/',
  path: '/data-config/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArchiveWarehouseIndexRoute =
  AppArchiveWarehouseIndexRouteImport.update({
    id: '/archive-warehouse/',
    path: '/archive-warehouse/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppArchiveSubmissionIndexRoute =
  AppArchiveSubmissionIndexRouteImport.update({
    id: '/archive-submission/',
    path: '/archive-submission/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppArchiveReviewIndexRoute = AppArchiveReviewIndexRouteImport.update({
  id: '/archive-review/',
  path: '/archive-review/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArchivePermissionIndexRoute =
  AppArchivePermissionIndexRouteImport.update({
    id: '/archive-permission/',
    path: '/archive-permission/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppArchiveFondsIndexRoute = AppArchiveFondsIndexRouteImport.update({
  id: '/archive-fonds/',
  path: '/archive-fonds/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArchiveDossiersIndexRoute = AppArchiveDossiersIndexRouteImport.update({
  id: '/archive-dossiers/',
  path: '/archive-dossiers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArchiveConfigIndexRoute = AppArchiveConfigIndexRouteImport.update({
  id: '/archive-config/',
  path: '/archive-config/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlanManagementPlanIdRoute = AppPlanManagementPlanIdRouteImport.update({
  id: '/plan-management/$planId',
  path: '/plan-management/$planId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPhysicalWarehouseConfigRoute =
  AppPhysicalWarehouseConfigRouteImport.update({
    id: '/physical-warehouse/config',
    path: '/physical-warehouse/config',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPermissionsFunctionMatrixRoute =
  AppPermissionsFunctionMatrixRouteImport.update({
    id: '/permissions/function-matrix',
    path: '/permissions/function-matrix',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDataConfigWatermarkConfigsRoute =
  AppDataConfigWatermarkConfigsRouteImport.update({
    id: '/data-config/watermark-configs',
    path: '/data-config/watermark-configs',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDataConfigNotificationConfigsRoute =
  AppDataConfigNotificationConfigsRouteImport.update({
    id: '/data-config/notification-configs',
    path: '/data-config/notification-configs',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDataConfigMetadataExportPresetsRoute =
  AppDataConfigMetadataExportPresetsRouteImport.update({
    id: '/data-config/metadata-export-presets',
    path: '/data-config/metadata-export-presets',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDataConfigDocumentTypesRoute =
  AppDataConfigDocumentTypesRouteImport.update({
    id: '/data-config/document-types',
    path: '/data-config/document-types',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDataConfigDocumentAssignmentRoute =
  AppDataConfigDocumentAssignmentRouteImport.update({
    id: '/data-config/document-assignment',
    path: '/data-config/document-assignment',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppArchiveDossiersFondIdIndexRoute =
  AppArchiveDossiersFondIdIndexRouteImport.update({
    id: '/archive-dossiers/$fondId/',
    path: '/archive-dossiers/$fondId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppArchiveDossiersFondIdDossierIdRoute =
  AppArchiveDossiersFondIdDossierIdRouteImport.update({
    id: '/archive-dossiers/$fondId/$dossierId',
    path: '/archive-dossiers/$fondId/$dossierId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/app/': typeof AppIndexRoute
  '/app/data-config/document-assignment': typeof AppDataConfigDocumentAssignmentRoute
  '/app/data-config/document-types': typeof AppDataConfigDocumentTypesRoute
  '/app/data-config/metadata-export-presets': typeof AppDataConfigMetadataExportPresetsRoute
  '/app/data-config/notification-configs': typeof AppDataConfigNotificationConfigsRoute
  '/app/data-config/watermark-configs': typeof AppDataConfigWatermarkConfigsRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/app/permissions/function-matrix': typeof AppPermissionsFunctionMatrixRoute
  '/app/physical-warehouse/config': typeof AppPhysicalWarehouseConfigRoute
  '/app/plan-management/$planId': typeof AppPlanManagementPlanIdRoute
  '/app/archive-config': typeof AppArchiveConfigIndexRoute
  '/app/archive-dossiers': typeof AppArchiveDossiersIndexRoute
  '/app/archive-fonds': typeof AppArchiveFondsIndexRoute
  '/app/archive-permission': typeof AppArchivePermissionIndexRoute
  '/app/archive-review': typeof AppArchiveReviewIndexRoute
  '/app/archive-submission': typeof AppArchiveSubmissionIndexRoute
  '/app/archive-warehouse': typeof AppArchiveWarehouseIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/data-config': typeof AppDataConfigIndexRoute
  '/app/data': typeof AppDataIndexRoute
  '/app/dossier-types': typeof AppDossierTypesIndexRoute
  '/app/dossiers': typeof AppDossiersIndexRoute
  '/app/general-catalog': typeof AppGeneralCatalogIndexRoute
  '/app/groups': typeof AppGroupsIndexRoute
  '/app/inventories': typeof AppInventoriesIndexRoute
  '/app/kpi': typeof AppKpiIndexRoute
  '/app/permissions': typeof AppPermissionsIndexRoute
  '/app/physical-warehouse': typeof AppPhysicalWarehouseIndexRoute
  '/app/plan-management': typeof AppPlanManagementIndexRoute
  '/app/project-manager': typeof AppProjectManagerIndexRoute
  '/app/retention-periods': typeof AppRetentionPeriodsIndexRoute
  '/app/review': typeof AppReviewIndexRoute
  '/app/scan-intake': typeof AppScanIntakeIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/warehouse-management': typeof AppWarehouseManagementIndexRoute
  '/app/archive-dossiers/$fondId/$dossierId': typeof AppArchiveDossiersFondIdDossierIdRoute
  '/app/archive-dossiers/$fondId': typeof AppArchiveDossiersFondIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/app': typeof AppIndexRoute
  '/app/data-config/document-assignment': typeof AppDataConfigDocumentAssignmentRoute
  '/app/data-config/document-types': typeof AppDataConfigDocumentTypesRoute
  '/app/data-config/metadata-export-presets': typeof AppDataConfigMetadataExportPresetsRoute
  '/app/data-config/notification-configs': typeof AppDataConfigNotificationConfigsRoute
  '/app/data-config/watermark-configs': typeof AppDataConfigWatermarkConfigsRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/app/permissions/function-matrix': typeof AppPermissionsFunctionMatrixRoute
  '/app/physical-warehouse/config': typeof AppPhysicalWarehouseConfigRoute
  '/app/plan-management/$planId': typeof AppPlanManagementPlanIdRoute
  '/app/archive-config': typeof AppArchiveConfigIndexRoute
  '/app/archive-dossiers': typeof AppArchiveDossiersIndexRoute
  '/app/archive-fonds': typeof AppArchiveFondsIndexRoute
  '/app/archive-permission': typeof AppArchivePermissionIndexRoute
  '/app/archive-review': typeof AppArchiveReviewIndexRoute
  '/app/archive-submission': typeof AppArchiveSubmissionIndexRoute
  '/app/archive-warehouse': typeof AppArchiveWarehouseIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/data-config': typeof AppDataConfigIndexRoute
  '/app/data': typeof AppDataIndexRoute
  '/app/dossier-types': typeof AppDossierTypesIndexRoute
  '/app/dossiers': typeof AppDossiersIndexRoute
  '/app/general-catalog': typeof AppGeneralCatalogIndexRoute
  '/app/groups': typeof AppGroupsIndexRoute
  '/app/inventories': typeof AppInventoriesIndexRoute
  '/app/kpi': typeof AppKpiIndexRoute
  '/app/permissions': typeof AppPermissionsIndexRoute
  '/app/physical-warehouse': typeof AppPhysicalWarehouseIndexRoute
  '/app/plan-management': typeof AppPlanManagementIndexRoute
  '/app/project-manager': typeof AppProjectManagerIndexRoute
  '/app/retention-periods': typeof AppRetentionPeriodsIndexRoute
  '/app/review': typeof AppReviewIndexRoute
  '/app/scan-intake': typeof AppScanIntakeIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/warehouse-management': typeof AppWarehouseManagementIndexRoute
  '/app/archive-dossiers/$fondId/$dossierId': typeof AppArchiveDossiersFondIdDossierIdRoute
  '/app/archive-dossiers/$fondId': typeof AppArchiveDossiersFondIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/app/': typeof AppIndexRoute
  '/app/data-config/document-assignment': typeof AppDataConfigDocumentAssignmentRoute
  '/app/data-config/document-types': typeof AppDataConfigDocumentTypesRoute
  '/app/data-config/metadata-export-presets': typeof AppDataConfigMetadataExportPresetsRoute
  '/app/data-config/notification-configs': typeof AppDataConfigNotificationConfigsRoute
  '/app/data-config/watermark-configs': typeof AppDataConfigWatermarkConfigsRoute
  '/app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/app/permissions/function-matrix': typeof AppPermissionsFunctionMatrixRoute
  '/app/physical-warehouse/config': typeof AppPhysicalWarehouseConfigRoute
  '/app/plan-management/$planId': typeof AppPlanManagementPlanIdRoute
  '/app/archive-config/': typeof AppArchiveConfigIndexRoute
  '/app/archive-dossiers/': typeof AppArchiveDossiersIndexRoute
  '/app/archive-fonds/': typeof AppArchiveFondsIndexRoute
  '/app/archive-permission/': typeof AppArchivePermissionIndexRoute
  '/app/archive-review/': typeof AppArchiveReviewIndexRoute
  '/app/archive-submission/': typeof AppArchiveSubmissionIndexRoute
  '/app/archive-warehouse/': typeof AppArchiveWarehouseIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/data-config/': typeof AppDataConfigIndexRoute
  '/app/data/': typeof AppDataIndexRoute
  '/app/dossier-types/': typeof AppDossierTypesIndexRoute
  '/app/dossiers/': typeof AppDossiersIndexRoute
  '/app/general-catalog/': typeof AppGeneralCatalogIndexRoute
  '/app/groups/': typeof AppGroupsIndexRoute
  '/app/inventories/': typeof AppInventoriesIndexRoute
  '/app/kpi/': typeof AppKpiIndexRoute
  '/app/permissions/': typeof AppPermissionsIndexRoute
  '/app/physical-warehouse/': typeof AppPhysicalWarehouseIndexRoute
  '/app/plan-management/': typeof AppPlanManagementIndexRoute
  '/app/project-manager/': typeof AppProjectManagerIndexRoute
  '/app/retention-periods/': typeof AppRetentionPeriodsIndexRoute
  '/app/review/': typeof AppReviewIndexRoute
  '/app/scan-intake/': typeof AppScanIntakeIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/warehouse-management/': typeof AppWarehouseManagementIndexRoute
  '/app/archive-dossiers/$fondId/$dossierId': typeof AppArchiveDossiersFondIdDossierIdRoute
  '/app/archive-dossiers/$fondId/': typeof AppArchiveDossiersFondIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/access-denied'
    | '/login'
    | '/test'
    | '/app/'
    | '/app/data-config/document-assignment'
    | '/app/data-config/document-types'
    | '/app/data-config/metadata-export-presets'
    | '/app/data-config/notification-configs'
    | '/app/data-config/watermark-configs'
    | '/app/groups/$groupId'
    | '/app/permissions/function-matrix'
    | '/app/physical-warehouse/config'
    | '/app/plan-management/$planId'
    | '/app/archive-config'
    | '/app/archive-dossiers'
    | '/app/archive-fonds'
    | '/app/archive-permission'
    | '/app/archive-review'
    | '/app/archive-submission'
    | '/app/archive-warehouse'
    | '/app/dashboard'
    | '/app/data-config'
    | '/app/data'
    | '/app/dossier-types'
    | '/app/dossiers'
    | '/app/general-catalog'
    | '/app/groups'
    | '/app/inventories'
    | '/app/kpi'
    | '/app/permissions'
    | '/app/physical-warehouse'
    | '/app/plan-management'
    | '/app/project-manager'
    | '/app/retention-periods'
    | '/app/review'
    | '/app/scan-intake'
    | '/app/users'
    | '/app/warehouse-management'
    | '/app/archive-dossiers/$fondId/$dossierId'
    | '/app/archive-dossiers/$fondId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/login'
    | '/test'
    | '/app'
    | '/app/data-config/document-assignment'
    | '/app/data-config/document-types'
    | '/app/data-config/metadata-export-presets'
    | '/app/data-config/notification-configs'
    | '/app/data-config/watermark-configs'
    | '/app/groups/$groupId'
    | '/app/permissions/function-matrix'
    | '/app/physical-warehouse/config'
    | '/app/plan-management/$planId'
    | '/app/archive-config'
    | '/app/archive-dossiers'
    | '/app/archive-fonds'
    | '/app/archive-permission'
    | '/app/archive-review'
    | '/app/archive-submission'
    | '/app/archive-warehouse'
    | '/app/dashboard'
    | '/app/data-config'
    | '/app/data'
    | '/app/dossier-types'
    | '/app/dossiers'
    | '/app/general-catalog'
    | '/app/groups'
    | '/app/inventories'
    | '/app/kpi'
    | '/app/permissions'
    | '/app/physical-warehouse'
    | '/app/plan-management'
    | '/app/project-manager'
    | '/app/retention-periods'
    | '/app/review'
    | '/app/scan-intake'
    | '/app/users'
    | '/app/warehouse-management'
    | '/app/archive-dossiers/$fondId/$dossierId'
    | '/app/archive-dossiers/$fondId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/access-denied'
    | '/login'
    | '/test'
    | '/app/'
    | '/app/data-config/document-assignment'
    | '/app/data-config/document-types'
    | '/app/data-config/metadata-export-presets'
    | '/app/data-config/notification-configs'
    | '/app/data-config/watermark-configs'
    | '/app/groups/$groupId'
    | '/app/permissions/function-matrix'
    | '/app/physical-warehouse/config'
    | '/app/plan-management/$planId'
    | '/app/archive-config/'
    | '/app/archive-dossiers/'
    | '/app/archive-fonds/'
    | '/app/archive-permission/'
    | '/app/archive-review/'
    | '/app/archive-submission/'
    | '/app/archive-warehouse/'
    | '/app/dashboard/'
    | '/app/data-config/'
    | '/app/data/'
    | '/app/dossier-types/'
    | '/app/dossiers/'
    | '/app/general-catalog/'
    | '/app/groups/'
    | '/app/inventories/'
    | '/app/kpi/'
    | '/app/permissions/'
    | '/app/physical-warehouse/'
    | '/app/plan-management/'
    | '/app/project-manager/'
    | '/app/retention-periods/'
    | '/app/review/'
    | '/app/scan-intake/'
    | '/app/users/'
    | '/app/warehouse-management/'
    | '/app/archive-dossiers/$fondId/$dossierId'
    | '/app/archive-dossiers/$fondId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/warehouse-management/': {
      id: '/app/warehouse-management/'
      path: '/warehouse-management'
      fullPath: '/app/warehouse-management'
      preLoaderRoute: typeof AppWarehouseManagementIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/scan-intake/': {
      id: '/app/scan-intake/'
      path: '/scan-intake'
      fullPath: '/app/scan-intake'
      preLoaderRoute: typeof AppScanIntakeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/review/': {
      id: '/app/review/'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/retention-periods/': {
      id: '/app/retention-periods/'
      path: '/retention-periods'
      fullPath: '/app/retention-periods'
      preLoaderRoute: typeof AppRetentionPeriodsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/project-manager/': {
      id: '/app/project-manager/'
      path: '/project-manager'
      fullPath: '/app/project-manager'
      preLoaderRoute: typeof AppProjectManagerIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/plan-management/': {
      id: '/app/plan-management/'
      path: '/plan-management'
      fullPath: '/app/plan-management'
      preLoaderRoute: typeof AppPlanManagementIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/physical-warehouse/': {
      id: '/app/physical-warehouse/'
      path: '/physical-warehouse'
      fullPath: '/app/physical-warehouse'
      preLoaderRoute: typeof AppPhysicalWarehouseIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/permissions/': {
      id: '/app/permissions/'
      path: '/permissions'
      fullPath: '/app/permissions'
      preLoaderRoute: typeof AppPermissionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/kpi/': {
      id: '/app/kpi/'
      path: '/kpi'
      fullPath: '/app/kpi'
      preLoaderRoute: typeof AppKpiIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventories/': {
      id: '/app/inventories/'
      path: '/inventories'
      fullPath: '/app/inventories'
      preLoaderRoute: typeof AppInventoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/groups/': {
      id: '/app/groups/'
      path: '/groups'
      fullPath: '/app/groups'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/general-catalog/': {
      id: '/app/general-catalog/'
      path: '/general-catalog'
      fullPath: '/app/general-catalog'
      preLoaderRoute: typeof AppGeneralCatalogIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dossiers/': {
      id: '/app/dossiers/'
      path: '/dossiers'
      fullPath: '/app/dossiers'
      preLoaderRoute: typeof AppDossiersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dossier-types/': {
      id: '/app/dossier-types/'
      path: '/dossier-types'
      fullPath: '/app/dossier-types'
      preLoaderRoute: typeof AppDossierTypesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/data/': {
      id: '/app/data/'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/data-config/': {
      id: '/app/data-config/'
      path: '/data-config'
      fullPath: '/app/data-config'
      preLoaderRoute: typeof AppDataConfigIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-warehouse/': {
      id: '/app/archive-warehouse/'
      path: '/archive-warehouse'
      fullPath: '/app/archive-warehouse'
      preLoaderRoute: typeof AppArchiveWarehouseIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-submission/': {
      id: '/app/archive-submission/'
      path: '/archive-submission'
      fullPath: '/app/archive-submission'
      preLoaderRoute: typeof AppArchiveSubmissionIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-review/': {
      id: '/app/archive-review/'
      path: '/archive-review'
      fullPath: '/app/archive-review'
      preLoaderRoute: typeof AppArchiveReviewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-permission/': {
      id: '/app/archive-permission/'
      path: '/archive-permission'
      fullPath: '/app/archive-permission'
      preLoaderRoute: typeof AppArchivePermissionIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-fonds/': {
      id: '/app/archive-fonds/'
      path: '/archive-fonds'
      fullPath: '/app/archive-fonds'
      preLoaderRoute: typeof AppArchiveFondsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-dossiers/': {
      id: '/app/archive-dossiers/'
      path: '/archive-dossiers'
      fullPath: '/app/archive-dossiers'
      preLoaderRoute: typeof AppArchiveDossiersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-config/': {
      id: '/app/archive-config/'
      path: '/archive-config'
      fullPath: '/app/archive-config'
      preLoaderRoute: typeof AppArchiveConfigIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/plan-management/$planId': {
      id: '/app/plan-management/$planId'
      path: '/plan-management/$planId'
      fullPath: '/app/plan-management/$planId'
      preLoaderRoute: typeof AppPlanManagementPlanIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/physical-warehouse/config': {
      id: '/app/physical-warehouse/config'
      path: '/physical-warehouse/config'
      fullPath: '/app/physical-warehouse/config'
      preLoaderRoute: typeof AppPhysicalWarehouseConfigRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/permissions/function-matrix': {
      id: '/app/permissions/function-matrix'
      path: '/permissions/function-matrix'
      fullPath: '/app/permissions/function-matrix'
      preLoaderRoute: typeof AppPermissionsFunctionMatrixRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/groups/$groupId': {
      id: '/app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/app/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/data-config/watermark-configs': {
      id: '/app/data-config/watermark-configs'
      path: '/data-config/watermark-configs'
      fullPath: '/app/data-config/watermark-configs'
      preLoaderRoute: typeof AppDataConfigWatermarkConfigsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/data-config/notification-configs': {
      id: '/app/data-config/notification-configs'
      path: '/data-config/notification-configs'
      fullPath: '/app/data-config/notification-configs'
      preLoaderRoute: typeof AppDataConfigNotificationConfigsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/data-config/metadata-export-presets': {
      id: '/app/data-config/metadata-export-presets'
      path: '/data-config/metadata-export-presets'
      fullPath: '/app/data-config/metadata-export-presets'
      preLoaderRoute: typeof AppDataConfigMetadataExportPresetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/data-config/document-types': {
      id: '/app/data-config/document-types'
      path: '/data-config/document-types'
      fullPath: '/app/data-config/document-types'
      preLoaderRoute: typeof AppDataConfigDocumentTypesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/data-config/document-assignment': {
      id: '/app/data-config/document-assignment'
      path: '/data-config/document-assignment'
      fullPath: '/app/data-config/document-assignment'
      preLoaderRoute: typeof AppDataConfigDocumentAssignmentRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-dossiers/$fondId/': {
      id: '/app/archive-dossiers/$fondId/'
      path: '/archive-dossiers/$fondId'
      fullPath: '/app/archive-dossiers/$fondId'
      preLoaderRoute: typeof AppArchiveDossiersFondIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive-dossiers/$fondId/$dossierId': {
      id: '/app/archive-dossiers/$fondId/$dossierId'
      path: '/archive-dossiers/$fondId/$dossierId'
      fullPath: '/app/archive-dossiers/$fondId/$dossierId'
      preLoaderRoute: typeof AppArchiveDossiersFondIdDossierIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDataConfigDocumentAssignmentRoute: typeof AppDataConfigDocumentAssignmentRoute
  AppDataConfigDocumentTypesRoute: typeof AppDataConfigDocumentTypesRoute
  AppDataConfigMetadataExportPresetsRoute: typeof AppDataConfigMetadataExportPresetsRoute
  AppDataConfigNotificationConfigsRoute: typeof AppDataConfigNotificationConfigsRoute
  AppDataConfigWatermarkConfigsRoute: typeof AppDataConfigWatermarkConfigsRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppPermissionsFunctionMatrixRoute: typeof AppPermissionsFunctionMatrixRoute
  AppPhysicalWarehouseConfigRoute: typeof AppPhysicalWarehouseConfigRoute
  AppPlanManagementPlanIdRoute: typeof AppPlanManagementPlanIdRoute
  AppArchiveConfigIndexRoute: typeof AppArchiveConfigIndexRoute
  AppArchiveDossiersIndexRoute: typeof AppArchiveDossiersIndexRoute
  AppArchiveFondsIndexRoute: typeof AppArchiveFondsIndexRoute
  AppArchivePermissionIndexRoute: typeof AppArchivePermissionIndexRoute
  AppArchiveReviewIndexRoute: typeof AppArchiveReviewIndexRoute
  AppArchiveSubmissionIndexRoute: typeof AppArchiveSubmissionIndexRoute
  AppArchiveWarehouseIndexRoute: typeof AppArchiveWarehouseIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDataConfigIndexRoute: typeof AppDataConfigIndexRoute
  AppDataIndexRoute: typeof AppDataIndexRoute
  AppDossierTypesIndexRoute: typeof AppDossierTypesIndexRoute
  AppDossiersIndexRoute: typeof AppDossiersIndexRoute
  AppGeneralCatalogIndexRoute: typeof AppGeneralCatalogIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppInventoriesIndexRoute: typeof AppInventoriesIndexRoute
  AppKpiIndexRoute: typeof AppKpiIndexRoute
  AppPermissionsIndexRoute: typeof AppPermissionsIndexRoute
  AppPhysicalWarehouseIndexRoute: typeof AppPhysicalWarehouseIndexRoute
  AppPlanManagementIndexRoute: typeof AppPlanManagementIndexRoute
  AppProjectManagerIndexRoute: typeof AppProjectManagerIndexRoute
  AppRetentionPeriodsIndexRoute: typeof AppRetentionPeriodsIndexRoute
  AppReviewIndexRoute: typeof AppReviewIndexRoute
  AppScanIntakeIndexRoute: typeof AppScanIntakeIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppWarehouseManagementIndexRoute: typeof AppWarehouseManagementIndexRoute
  AppArchiveDossiersFondIdDossierIdRoute: typeof AppArchiveDossiersFondIdDossierIdRoute
  AppArchiveDossiersFondIdIndexRoute: typeof AppArchiveDossiersFondIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDataConfigDocumentAssignmentRoute: AppDataConfigDocumentAssignmentRoute,
  AppDataConfigDocumentTypesRoute: AppDataConfigDocumentTypesRoute,
  AppDataConfigMetadataExportPresetsRoute:
    AppDataConfigMetadataExportPresetsRoute,
  AppDataConfigNotificationConfigsRoute: AppDataConfigNotificationConfigsRoute,
  AppDataConfigWatermarkConfigsRoute: AppDataConfigWatermarkConfigsRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppPermissionsFunctionMatrixRoute: AppPermissionsFunctionMatrixRoute,
  AppPhysicalWarehouseConfigRoute: AppPhysicalWarehouseConfigRoute,
  AppPlanManagementPlanIdRoute: AppPlanManagementPlanIdRoute,
  AppArchiveConfigIndexRoute: AppArchiveConfigIndexRoute,
  AppArchiveDossiersIndexRoute: AppArchiveDossiersIndexRoute,
  AppArchiveFondsIndexRoute: AppArchiveFondsIndexRoute,
  AppArchivePermissionIndexRoute: AppArchivePermissionIndexRoute,
  AppArchiveReviewIndexRoute: AppArchiveReviewIndexRoute,
  AppArchiveSubmissionIndexRoute: AppArchiveSubmissionIndexRoute,
  AppArchiveWarehouseIndexRoute: AppArchiveWarehouseIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDataConfigIndexRoute: AppDataConfigIndexRoute,
  AppDataIndexRoute: AppDataIndexRoute,
  AppDossierTypesIndexRoute: AppDossierTypesIndexRoute,
  AppDossiersIndexRoute: AppDossiersIndexRoute,
  AppGeneralCatalogIndexRoute: AppGeneralCatalogIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppInventoriesIndexRoute: AppInventoriesIndexRoute,
  AppKpiIndexRoute: AppKpiIndexRoute,
  AppPermissionsIndexRoute: AppPermissionsIndexRoute,
  AppPhysicalWarehouseIndexRoute: AppPhysicalWarehouseIndexRoute,
  AppPlanManagementIndexRoute: AppPlanManagementIndexRoute,
  AppProjectManagerIndexRoute: AppProjectManagerIndexRoute,
  AppRetentionPeriodsIndexRoute: AppRetentionPeriodsIndexRoute,
  AppReviewIndexRoute: AppReviewIndexRoute,
  AppScanIntakeIndexRoute: AppScanIntakeIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppWarehouseManagementIndexRoute: AppWarehouseManagementIndexRoute,
  AppArchiveDossiersFondIdDossierIdRoute:
    AppArchiveDossiersFondIdDossierIdRoute,
  AppArchiveDossiersFondIdIndexRoute: AppArchiveDossiersFondIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
