export const ARCHIVE_STORAGE_STATE_VALUES = [
  "STORING",
  "IN_USE",
  "TEMPORARILY_LOCKED",
  "PENDING_DESTRUCTION",
  "DESTROYED",
  "TRANSFERRED_TO_HISTORICAL_ARCHIVE",
] as const

export type ArchiveStorageState = (typeof ARCHIVE_STORAGE_STATE_VALUES)[number]

export const ArchiveStorageState = {
  STORING: "STORING",
  IN_USE: "IN_USE",
  TEMPORARILY_LOCKED: "TEMPORARILY_LOCKED",
  PENDING_DESTRUCTION: "PENDING_DESTRUCTION",
  DESTROYED: "DESTROYED",
  TRANSFERRED_TO_HISTORICAL_ARCHIVE: "TRANSFERRED_TO_HISTORICAL_ARCHIVE",
} as const satisfies Record<string, ArchiveStorageState>
