/**
 * Seed Data Constants
 *
 * Centralized data definitions for seeding
 */

/**
 * Seed version - increment this when seed data changes
 * This is used by the test setup to determine if re-seeding is needed
 */
export const SEED_VERSION = "v0.0.15";

// User data with credentials
export const USERS = [
  {
    email: "admin@sohoa.vn",
    password: "Admin@sohoa2026",
    fullName: "System Administrator",
    role: "admin",
  },
  {
    email: "admin@fsi.com",
    password: "fsi@12345",
    fullName: "Quản trị viên",
    role: "quantri",
  },
  {
    email: "pm1@fsi.com",
    password: "fsi@12345",
    fullName: "Quản trị dự án 1",
    role: "pm",
  },
  {
    email: "pm2@fsi.com",
    password: "fsi@12345",
    fullName: "Quản trị dự án 2",
    role: "pm",
  },
  {
    email: "qc1@fsi.com",
    password: "fsi@12345",
    fullName: "Kiểm duyệt 1",
    role: "qc",
  },
  {
    email: "qc2@fsi.com",
    password: "fsi@12345",
    fullName: "Kiểm duyệt 2",
    role: "qc",
  },
  {
    email: "editor1@fsi.com",
    password: "fsi@12345",
    fullName: "Biên tập viên 1",
    role: "editor",
  },
  {
    email: "editor2@fsi.com",
    password: "fsi@12345",
    fullName: "Biên tập viên 2",
    role: "editor",
  },
  {
    email: "editor3@fsi.com",
    password: "fsi@12345",
    fullName: "Biên tập viên 3",
    role: "editor",
  },
];

// Role definitions
export const ROLE_DEFINITIONS = [
  {
    id: "admin",
    name: "Administrator",
    description: "System administrator with full access",
    rules: JSON.stringify({
      permissions: ["*"],
      restrictions: [],
    }),
    hiddenModules: JSON.stringify([]),
    hiddenPermissions: JSON.stringify([]),
    isBaseRole: true,
  },
  {
    id: "qc",
    name: "QC",
    description: "Quality checker with data-entry checker access",
    rules: JSON.stringify({
      permissions: [
        "dashboard.qc",
        "groups.read",
        "projects.read",
        "data-entry.*",
        "groups.start_workflow",
        "groups.revoke",
        "metadata.permissions.manage",
        "dossiers.read",
        "folders.*",
        "document-types.read",
        "metadata.templates.manage",
        "dossiers.write",
      ],
      restrictions: [],
    }),
    hiddenModules: JSON.stringify([]),
    hiddenPermissions: JSON.stringify([]),
    isBaseRole: true,
  },
  {
    id: "editor",
    name: "Editor",
    description: "Data entry maker with folder and dossier access",
    rules: JSON.stringify({
      permissions: [
        "data-entry.maker",
        "dashboard.editor",
        "groups.read",
        "dossiers.write",
      ],
      restrictions: [],
    }),
    hiddenModules: JSON.stringify([]),
    hiddenPermissions: JSON.stringify([]),
    isBaseRole: true,
  },
  {
    id: "quantri",
    name: "Quản trị hệ thống",
    description: "quản lý toàn bộ",
    rules: JSON.stringify({
      permissions: [
        "projects.*",
        "project-plans.*",
        "groups.*",
        "scan-intake.*",
        "data-entry.*",
        "dossiers.*",
        "folders.*",
        "users.*",
        "fonds.*",
        "inventories.*",
        "dossier-types.*",
        "audit_logs.*",
        "retention-periods.*",
        "security-levels.*",
        "dashboard.editor",
        "dashboard.qc",
        "dashboard.admin",
        "dashboard.admin.summary",
        "dashboard.admin.dossier_status_chart",
        "dashboard.admin.project_status_chart",
        "dashboard.admin.dossier_trend_chart",
        "dashboard.admin.system_performance",
        "dashboard.admin.employee_kpis",
        "dashboard.admin.group_performance_chart",
        "document-types.*",
        "metadata.permissions.manage",
        "metadata.export_presets.manage",
        "metadata.extract.trigger",
        "ocr-control.*",
        "metadata.templates.manage",
        "metadata.extract.settings.read",
        "roles.manage",
        "dashboard.admin.unassigned",
        "dashboard.admin.read_all",
      ],
      restrictions: [],
    }),
    hiddenModules: JSON.stringify([]),
    hiddenPermissions: JSON.stringify([
      "library.exploitation.read",
      "library.borrow.request",
      "library.borrow.review",
      "library.borrow.approval-config.manage",
      "retention-periods.read",
      "retention-periods.create",
      "retention-periods.update",
      "retention-periods.delete",
      "metadata.extract.settings.read",
      "metadata.extract.settings.update",
      "metadata.extract.trigger",
      "metadata.naming.manage",
      "archive.warehouse.read",
      "archive.warehouse.edit",
      "archive.warehouse.configure_security",
      "archive.warehouse.delete",
      "archive.warehouse.reupload",
      "archive.permissions.manage",
      "archive.submit",
      "archive.review",
      "archive.config.manage",
      "physical-warehouse.item.read",
      "physical-warehouse.location.manage",
      "physical-warehouse.warehouse.manage",
      "archive.disposal.read",
      "archive.disposal.create",
      "archive.disposal.update",
      "archive.disposal.submit",
      "archive.disposal.council.read",
      "archive.disposal.council.create",
      "archive.disposal.council.update",
      "archive.disposal.council.finalize",
      "archive.disposal.council.publish",
      "archive.disposal.council.chair_decide",
      "archive.disposal.settings.manage",
      "archive.disposal.destroy",
      "roles.manage",
      "watermark.config.read",
      "watermark.config.create",
      "watermark.config.update",
      "watermark.config.delete",
      "document-types.read",
      "document-types.create",
      "document-types.update",
      "document-types.delete",
      "notifications.config.manage",
      "metadata.hidden_fields.update",
      "metadata.hidden_fields.read",
      "archive.warehouse.download",
      "auth.two_factor_require",
    ]),
    isBaseRole: true,
  },
  {
    id: "pm",
    name: "Quản trị dự án",
    description: "Project manager with full operational access",
    rules: JSON.stringify({
      permissions: [
        "dashboard.admin",
        "projects.read",
        "projects.create",
        "projects.update",
        "projects.delete",
        "project-plans.read",
        "project-plans.create",
        "project-plans.update",
        "project-plans.delete",
        "scan-intake.use",
        "data-entry.maker",
        "data-entry.checker",
        "dossiers.read",
        "dossiers.write",
        "dossiers.assign",
        "dossiers.export",
        "dossiers.export_any_status",
        "dossiers.sign",
        "dossiers.direct_approve",
        "dossiers.metadata.summary.edit",
        "folders.browse_all",
        "folders.browse_assigned",
        "fonds.read",
        "fonds.create",
        "fonds.update",
        "fonds.delete",
        "inventories.read",
        "inventories.create",
        "inventories.update",
        "inventories.delete",
        "dossier-types.read",
        "dossier-types.create",
        "dossier-types.update",
        "dossier-types.delete",
        "notifications.config.manage",
        "audit_logs.*",
        "metadata.templates.manage",
        "metadata.permissions.manage",
        "metadata.naming.manage",
        "metadata.export_presets.manage",
        "document-types.*",
        "ocr-control.*",
        "dashboard.admin.summary",
        "dashboard.admin.dossier_status_chart",
        "dashboard.admin.project_status_chart",
        "dashboard.admin.dossier_trend_chart",
        "dashboard.admin.system_performance",
        "dashboard.admin.employee_kpis",
        "dashboard.admin.group_performance_chart",
        "groups.*",
        "archive.warehouse.download",
      ],
      restrictions: [],
    }),
    hiddenModules: JSON.stringify([]),
    hiddenPermissions: JSON.stringify([]),
    isBaseRole: true,
  },
];
